//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_QLTB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOHONG_THIETBI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAOHONG_THIETBI()
        {
            this.CHITIET_KEHOACH = new HashSet<CHITIET_KEHOACH>();
        }
    
        public string ID_BaoHong { get; set; }
        public string ThietBiNo { get; set; }
        public string NguoiBaoHongNo { get; set; }
        public string MoTaHong { get; set; }
        public string HinhAnh { get; set; }
        public System.DateTime NgayBao { get; set; }
        public string MucDoUuTien { get; set; }
        public string TrangThai { get; set; }
    
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual THIETBI THIETBI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_KEHOACH> CHITIET_KEHOACH { get; set; }
    }
}
