//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_QLTB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_DEXUAT
    {
        public string ID_ChiTiet { get; set; }
        public string DeXuatNo { get; set; }
        public string DanhMucNo { get; set; }
        public string TenThietBiDeXuat { get; set; }
        public int SoLuong { get; set; }
        public Nullable<decimal> GiaDuKien { get; set; }
        public string DonViTinh { get; set; }
    
        public virtual DANHMUC DANHMUC { get; set; }
        public virtual DEXUAT_MUASAM DEXUAT_MUASAM { get; set; }
    }
}
