//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_QLTB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_KIEMKE
    {
        public string ID_ChiTietKK { get; set; }
        public string KiemKeNo { get; set; }
        public string ThietBiNo { get; set; }
        public Nullable<int> SoLuongThucTe { get; set; }
        public Nullable<int> SoLuongHeThong { get; set; }
        public string TinhTrangThucTe { get; set; }
        public Nullable<int> ChenhLech { get; set; }
        public string GhiChu { get; set; }
    
        public virtual KIEMKE KIEMKE { get; set; }
        public virtual THIETBI THIETBI { get; set; }
    }
}
