//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_QLTB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_KEHOACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHITIET_KEHOACH()
        {
            this.GHINHAN_SUA_CHUA = new HashSet<GHINHAN_SUA_CHUA>();
        }
    
        public string ID_ChiTietKH { get; set; }
        public string KeHoachNo { get; set; }
        public string ThietBiNo { get; set; }
        public string BaoHongNo { get; set; }
        public string GhiChuChiTiet { get; set; }
    
        public virtual BAOHONG_THIETBI BAOHONG_THIETBI { get; set; }
        public virtual KEHOACH_BAOTRI KEHOACH_BAOTRI { get; set; }
        public virtual THIETBI THIETBI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GHINHAN_SUA_CHUA> GHINHAN_SUA_CHUA { get; set; }
    }
}
