//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_QLTB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEXUAT_MUASAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEXUAT_MUASAM()
        {
            this.CHITIET_DEXUAT = new HashSet<CHITIET_DEXUAT>();
            this.LICHSUDUYETs = new HashSet<LICHSUDUYET>();
            this.THIETBIs = new HashSet<THIETBI>();
        }
    
        public string ID_DeXuat { get; set; }
        public string NguoiDeXuatNo { get; set; }
        public System.DateTime NgayDeXuat { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> CapDuyetHienTai { get; set; }
        public string NguoiDuyetCuoiNo { get; set; }
        public Nullable<System.DateTime> NgayDuyetCuoi { get; set; }
        public string LyDoTuChoi { get; set; }
        public string MoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_DEXUAT> CHITIET_DEXUAT { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHSUDUYET> LICHSUDUYETs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THIETBI> THIETBIs { get; set; }
    }
}
