//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_QLTB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GHINHAN_SUA_CHUA
    {
        public string ID_GhiNhan { get; set; }
        public string KeHoachNo { get; set; }
        public string ChiTietKeHoachNo { get; set; }
        public System.DateTime NgayThucHien { get; set; }
        public string KetQua { get; set; }
        public Nullable<decimal> ChiPhiThucTe { get; set; }
        public string TrangThaiSauSua { get; set; }
        public string HinhAnhSau { get; set; }
    
        public virtual CHITIET_KEHOACH CHITIET_KEHOACH { get; set; }
        public virtual KEHOACH_BAOTRI KEHOACH_BAOTRI { get; set; }
    }
}
