//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_QLTB
{
    using System;
    using System.Collections.Generic;
    
    public partial class KEHOACH_BAOTRI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KEHOACH_BAOTRI()
        {
            this.CHITIET_KEHOACH = new HashSet<CHITIET_KEHOACH>();
            this.GHINHAN_SUA_CHUA = new HashSet<GHINHAN_SUA_CHUA>();
        }
    
        public string ID_KeHoach { get; set; }
        public string NguoiLapNo { get; set; }
        public System.DateTime NgayLap { get; set; }
        public Nullable<System.DateTime> NgayDuKienHT { get; set; }
        public string LoaiKeHoach { get; set; }
        public string DonViThucHien { get; set; }
        public Nullable<decimal> ChiPhiDuKien { get; set; }
        public string TrangThai { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_KEHOACH> CHITIET_KEHOACH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GHINHAN_SUA_CHUA> GHINHAN_SUA_CHUA { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
    }
}
