//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_QLTB
{
    using System;
    using System.Collections.Generic;
    
    public partial class KIEMKE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KIEMKE()
        {
            this.CHITIET_KIEMKE = new HashSet<CHITIET_KIEMKE>();
        }
    
        public string ID_KiemKe { get; set; }
        public string NguoiThucHienNo { get; set; }
        public System.DateTime NgayKiemKe { get; set; }
        public string TrangThai { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_KIEMKE> CHITIET_KIEMKE { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
    }
}
