//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_QLTB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHSUDUYET
    {
        public string ID_LichSu { get; set; }
        public string DeXuatNo { get; set; }
        public Nullable<int> CapDuyet { get; set; }
        public string NguoiDuyetNo { get; set; }
        public System.DateTime ThoiGianDuyet { get; set; }
        public string TrangThaiSauDuyet { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DEXUAT_MUASAM DEXUAT_MUASAM { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
    }
}
