//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_QLTB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOIDUNG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NGUOIDUNG()
        {
            this.BAOHONG_THIETBI = new HashSet<BAOHONG_THIETBI>();
            this.DEXUAT_MUASAM = new HashSet<DEXUAT_MUASAM>();
            this.DEXUAT_MUASAM1 = new HashSet<DEXUAT_MUASAM>();
            this.KEHOACH_BAOTRI = new HashSet<KEHOACH_BAOTRI>();
            this.KIEMKEs = new HashSet<KIEMKE>();
            this.NGUOIDUNG_THONGBAO = new HashSet<NGUOIDUNG_THONGBAO>();
            this.THONGBAOs = new HashSet<THONGBAO>();
            this.VAITRO_NGUOIDUNG = new HashSet<VAITRO_NGUOIDUNG>();
        }
    
        public string ID_NguoiDung { get; set; }
        public string Khoa_BanNo { get; set; }
        public string Email { get; set; }
        public string MatKhau { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public bool TrangThaiTK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAOHONG_THIETBI> BAOHONG_THIETBI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEXUAT_MUASAM> DEXUAT_MUASAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEXUAT_MUASAM> DEXUAT_MUASAM1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KEHOACH_BAOTRI> KEHOACH_BAOTRI { get; set; }
        public virtual KHOA_PHONGBAN KHOA_PHONGBAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KIEMKE> KIEMKEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGUOIDUNG_THONGBAO> NGUOIDUNG_THONGBAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THONGBAO> THONGBAOs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VAITRO_NGUOIDUNG> VAITRO_NGUOIDUNG { get; set; }
    }
}
