//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_QLTB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOIDUNG_THONGBAO
    {
        public string ThongBaoNo { get; set; }
        public string NguoiNhanNo { get; set; }
        public bool TrangThaiDoc { get; set; }
    
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual THONGBAO THONGBAO { get; set; }
    }
}
