//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_QLTB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONG_THIETBI
    {
        public string ThietBiNo { get; set; }
        public string PhongNo { get; set; }
        public Nullable<System.DateTime> NgayHieuLuc { get; set; }
    
        public virtual PHONG PHONG { get; set; }
        public virtual THIETBI THIETBI { get; set; }
    }
}
