//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_QLTB
{
    using System;
    using System.Collections.Generic;
    
    public partial class THIETBI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THIETBI()
        {
            this.BAOHONG_THIETBI = new HashSet<BAOHONG_THIETBI>();
            this.CHITIET_KEHOACH = new HashSet<CHITIET_KEHOACH>();
            this.CHITIET_KIEMKE = new HashSet<CHITIET_KIEMKE>();
            this.PHONG_THIETBI = new HashSet<PHONG_THIETBI>();
        }
    
        public string ID_ThietBi { get; set; }
        public string DanhMucNo { get; set; }
        public string NhaCCNo { get; set; }
        public string KhoaPhongBan { get; set; }
        public string TenTB { get; set; }
        public string TrangThaiTB { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public string ThongSoKT { get; set; }
        public Nullable<int> SoSeri { get; set; }
        public string DeXuatNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAOHONG_THIETBI> BAOHONG_THIETBI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_KEHOACH> CHITIET_KEHOACH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_KIEMKE> CHITIET_KIEMKE { get; set; }
        public virtual DANHMUC DANHMUC { get; set; }
        public virtual KHOA_PHONGBAN KHOA_PHONGBAN { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHONG_THIETBI> PHONG_THIETBI { get; set; }
        public virtual DEXUAT_MUASAM DEXUAT_MUASAM { get; set; }
    }
}
