//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_QLTB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAITRO_NGUOIDUNG
    {
        public string NguoiDungNo { get; set; }
        public string VaiTroNo { get; set; }
        public Nullable<System.DateTime> NgayHieuLuc { get; set; }
    
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual VAITRO VAITRO { get; set; }
    }
}
