//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_QLTB
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_LichSuDuyet
    {
        public string ID_LichSu { get; set; }
        public string DeXuatNo { get; set; }
        public string NoiDungDeXuat { get; set; }
        public string TrangThaiHienTai { get; set; }
        public Nullable<int> CapDuyet { get; set; }
        public string TenCapDuyet { get; set; }
        public string NguoiDuyet { get; set; }
        public System.DateTime ThoiGianDuyet { get; set; }
        public string TrangThaiSauDuyet { get; set; }
        public string GhiChu { get; set; }
    }
}
