//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_QLTB
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_BaoHong_TrangThai
    {
        public string ID_BaoHong { get; set; }
        public System.DateTime NgayBao { get; set; }
        public string MucDoUuTien { get; set; }
        public string TrangThaiBaoHong { get; set; }
        public string MoTaHong { get; set; }
        public string TenTB { get; set; }
        public string TenDanhMuc { get; set; }
        public string NguoiBaoHong { get; set; }
        public string ID_KeHoach { get; set; }
        public string TrangThaiKeHoach { get; set; }
        public string LoaiKeHoach { get; set; }
    }
}
