//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_QLTB
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_BaoCaoTaiChinh
    {
        public string ID_ThietBi { get; set; }
        public string TenTB { get; set; }
        public string TenDanhMuc { get; set; }
        public string TenPhongBanKhoa { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public string TrangThaiTB { get; set; }
        public Nullable<decimal> TongChiPhiSuaChua { get; set; }
    }
}
