//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAPM_QLTB
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_KeHoach_ChiTiet
    {
        public string ID_KeHoach { get; set; }
        public System.DateTime NgayLap { get; set; }
        public Nullable<System.DateTime> NgayDuKienHT { get; set; }
        public string LoaiKeHoach { get; set; }
        public string TrangThaiKeHoach { get; set; }
        public string DonViThucHien { get; set; }
        public Nullable<decimal> ChiPhiDuKien { get; set; }
        public string NguoiLap { get; set; }
        public string ID_ChiTietKH { get; set; }
        public string TenTB { get; set; }
        public string TenDanhMuc { get; set; }
        public string BaoHongNo { get; set; }
        public string NguonGoc { get; set; }
        public string GhiChuChiTiet { get; set; }
    }
}
