-- Thêm vào migration: query schema bảng DEXUAT_MUASAM để kiểm tra tên cột
SELECT COLUMN_NAME, DATA_TYPE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'DEXUAT_MUASAM'
ORDER BY ORDINAL_POSITION;
GO

-- Query schema CHITIET_DEXUAT
SELECT COLUMN_NAME, DATA_TYPE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'CHITIET_DEXUAT'
ORDER BY ORDINAL_POSITION;
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'THONGBAO')
BEGIN
    CREATE TABLE THONGBAO (
        ID_ThongBao  NVARCHAR(50)  NOT NULL PRIMARY KEY DEFAULT NEWID(),
        NguoiNhanNo  NVARCHAR(50)  NOT NULL,   -- FK -> NGUOIDUNG.ID_NguoiDung
        TieuDe       NVARCHAR(255) NOT NULL,
        NoiDung      NVARCHAR(MAX) NULL,
        NgayTao      DATETIME      NOT NULL DEFAULT GETDATE(),
        LoaiThongBao NVARCHAR(50)  NULL,        -- approved | rejected | pending | system
        DaDoc        BIT           NOT NULL DEFAULT 0,
        CONSTRAINT FK_THONGBAO_NGUOIDUNG FOREIGN KEY (NguoiNhanNo)
            REFERENCES NGUOIDUNG(ID_NguoiDung)
    );
    PRINT 'Đã tạo bảng THONGBAO';
END
ELSE
BEGIN
    PRINT 'Bảng THONGBAO đã tồn tại';
END
GO

-- Đảm bảo cột NguoiDeXuatNo tồn tại trong DEXUAT_MUASAM
-- (thay thế cột NguoiDeXuat cũ nếu cần)
IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'DEXUAT_MUASAM' AND COLUMN_NAME = 'NguoiDeXuatNo'
)
BEGIN
    ALTER TABLE DEXUAT_MUASAM ADD NguoiDeXuatNo NVARCHAR(50) NULL;
    PRINT 'Đã thêm cột NguoiDeXuatNo vào DEXUAT_MUASAM';
END
GO

-- Đảm bảo cột GiaDuKien tồn tại trong CHITIET_DEXUAT
IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'CHITIET_DEXUAT' AND COLUMN_NAME = 'GiaDuKien'
)
BEGIN
    ALTER TABLE CHITIET_DEXUAT ADD GiaDuKien DECIMAL(18,2) NULL;
    PRINT 'Đã thêm cột GiaDuKien vào CHITIET_DEXUAT';
END
GO

-- Thêm cột ThietBiNo vào CHITIET_DEXUAT để link trực tiếp với THIETBI
IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME='CHITIET_DEXUAT' AND COLUMN_NAME='ThietBiNo'
)
BEGIN
    ALTER TABLE CHITIET_DEXUAT ADD ThietBiNo CHAR(10) NULL;
    PRINT 'Đã thêm cột ThietBiNo vào CHITIET_DEXUAT';
END
GO
